### ISSUE TITLE
Feature request: Add option for masking

### ISSUE THREAD

**Issue by GalOzRlz** [aarcangeli/load-dotenv#61]
Hi! I would love to see like a masking option either for files/specific vars or just the entire action

it's a simple step, as follows, that can be looped:

`echo "::add-mask::$ACCESS_TOKEN"`

**Comment by aarcangeli** [comment]
Hi @GalOzRlz, if I understand correctly, you're requesting an option to automatically mask variables loaded from a `.env` file.

```yaml
- uses: aarcangeli/load-dotenv@v1
  with:
    mask_variables: ACCESS_TOKEN
```

However, access tokens should **never** be committed to the repository or stored in a `.env` file within the project directory.
Instead, they should be stored as GitHub Actions secrets.
